substitutions:
  _REGION: asia-southeast1
  _AR_REPOSITORY: jobsrss
  _IMAGE_TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-api
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-api:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-api:latest
      - -f
      - backend/Dockerfile
      - backend
  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    waitFor: ["-"]
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-frontend:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-frontend:latest
      - -f
      - frontend/Dockerfile
      - frontend

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-api:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-api:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-frontend:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/jobsrss-frontend:latest

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

timeout: 2400s
